In [33]:
import torch
import torch.nn as nn

In [21]:
block_size=8
batch_size=4

In [22]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [23]:
with open('wizard_of_oz.txt','r',encoding='utf-8') as f:
    text=f.read()

In [24]:
char=sorted(set(text))
print(' the length of char is {}'.format(len(char)))
print(char)

 the length of char is 80
['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [25]:
string_to_int={ch:i for i, ch in enumerate(char)}
int_to_string={i:ch for i, ch in enumerate(char)}
encode=lambda s:[string_to_int[c] for c in s]
decode=lambda s:"".join([int_to_string[c] for c in s])

In [26]:
encoded_text=encode(text)

In [27]:
data=torch.Tensor(encoded_text)# dtype=torch.long) #dtype=torch.long

In [28]:
data[:10]

tensor([ 1.,  1., 28., 39., 42., 39., 44., 32., 49.,  1.])

# splitting data for training and validating

In [29]:
n=int(len(text)*0.8)
train_data=data[:n]
val_data=data[n:]

In [30]:

x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
    context=x[:t+1]
    target=y[t]
    print("when input is ",context,'target is ',target)

when input is  tensor([1.]) target is  tensor(1.)
when input is  tensor([1., 1.]) target is  tensor(28.)
when input is  tensor([ 1.,  1., 28.]) target is  tensor(39.)
when input is  tensor([ 1.,  1., 28., 39.]) target is  tensor(42.)
when input is  tensor([ 1.,  1., 28., 39., 42.]) target is  tensor(39.)
when input is  tensor([ 1.,  1., 28., 39., 42., 39.]) target is  tensor(44.)
when input is  tensor([ 1.,  1., 28., 39., 42., 39., 44.]) target is  tensor(32.)
when input is  tensor([ 1.,  1., 28., 39., 42., 39., 44., 32.]) target is  tensor(49.)


In [31]:
#softmax
tensor1=torch.Tensor([1,2,3,4,5])
softmax_tensor=F.softmax(tensor1,dim=0)

print(softmax_tensor)

tensor([0.0117, 0.0317, 0.0861, 0.2341, 0.6364])


In [34]:
#initializing an embedding layer
vocal_size=1000
embedding_layer=100
#Creating embedding layer
embedding=nn.Embedding(vocal_size,embedding_layer)
#initialising input
input_indice=torch.LongTensor([1,5,3,2])
#Applying the embedding layer
embedding_output=embedding(input_indice)
print(embedding_output.shape)

torch.Size([4, 100])


In [40]:
#Get batch function
def get_batch(split):
    data=train_data if split=='train' else val_data
    ix=torch.randint(len(data)-block_size,(batch_size,))
    print(ix)
    x=torch.stack([data[i:i+block_size] for i in ix])
    y=torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y


In [44]:
x, y=get_batch('train')

tensor([ 23549,  65827, 168137, 132011])
